### PR TITLE
added  rand_vec_spread_deg,rand_vec_magnitude

### PR DESCRIPTION
**Pull request by jf22201**
Ported functions, both used from_polar method from _Vec2 so I ported that as well. Also ported Vector and Point types from types.py.

### CODE REVIEW

**Comment by Cleptomania** [comment]
Hi, thanks for the PR, if you want to go ahead and port the whole Vec2 class you can. You can just add it to this PR and I can merge it when it's all done.

**Comment by jf22201** [comment]
> Hi, thanks for the PR, if you want to go ahead and port the whole Vec2 class you can. You can just add it to this PR and I can merge it when it's all done.

Sure, I'll give that an attempt.

**Comment by jf22201** [comment]
My latest commit has the rest of the methods for Vec2 ported as well as some minor modifications to the ported functions themselves.

**Comment by Cleptomania** [comment]
Could you add another commit with `cargo fmt` and make sure that `cargo clippy` passes as well? We just added these to the CI process so I haven't gotten contributing guidelines setup to include these steps yet. If you'd rather I can just merge it and fix the formatting/linting myself.

**Pull request merged**
